### ISSUE TITLE
Webpages

### ISSUE THREAD

**Issue by gponimansky** [Voidustries/Voidustries.github.io#1]
- [x] Addition of all the web pages.
- [x] Fixes to the links between web pages.
- [x] Addition of various filler information.

**Comment by StoneMonarch** [comment]
I should probably be testing on a private repo and then submit a pull when done. Ill do that.

**Comment by gponimansky** [comment]
Check off the list as you do the things above.

**Comment by StoneMonarch** [comment]
Will do, Ill submit a pull when ready.

**Comment by StoneMonarch** [comment]
Ready for pull
